<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий на hh.ru

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Исследование структуры данных

1. Прочитайте данные с помощью библиотеки Pandas. Совет: перед чтением обратите внимание на разделитель внутри файла.

In [ ]:
hh_data = pd.read_csv('data/dst-3.0_16_1_hh_database.csv', sep= ';')
hh_data.shape

Ответ: размерность таблицы (44744, 12)

2. Выведите несколько первых (последних) строк таблицы, чтобы убедиться в том, что ваши данные не повреждены. Ознакомьтесь с признаками и их структурой.

In [ ]:
hh_data.head()

In [ ]:
hh_data.tail()

Ответ: порядок слов в признаке «Пол, возраст» представлен в формате <Пол , возраст , дата рождения>

3. Выведите основную информацию о числе непустых значений в столбцах и их типах в таблице.

In [ ]:
hh_data.info()

Ответ: все столбцы имеют тип данных object

4. Обратите внимание на информацию о числе непустых значений.

In [ ]:
hh_data.count()

Ответ: признаки, в которых есть пропуски в данных: Последняя/нынешняя должность, Опыт работы, Последнее/нынешнее место работы

5. Выведите основную статистическую информацию о столбцах.

In [ ]:
hh_data.info()

In [ ]:
hh_data['Опыт работы'].nunique()

Ответ: 44413  уникальных значений содержится в столбце «Опыт работы»

In [ ]:
hh_data['Ищет работу на должность:'].mode()

Ответ: самая распространённая должность - Системный администратор

# Преобразование данных

1. Начнем с простого - с признака **"Образование и ВУЗ"**. Его текущий формат это: **<Уровень образования год выпуска ВУЗ специальность...>**. Например:
* Высшее образование 2016 Московский авиационный институт (национальный исследовательский университет)...
* Неоконченное высшее образование 2000  Балтийская государственная академия рыбопромыслового флота…
Нас будет интересовать только уровень образования.

Создайте с помощью функции-преобразования новый признак **"Образование"**, который должен иметь 4 категории: "высшее", "неоконченное высшее", "среднее специальное" и "среднее".

Выполните преобразование, ответьте на контрольные вопросы и удалите признак "Образование и ВУЗ".

Совет: обратите внимание на структуру текста в столбце **"Образование и ВУЗ"**. Гарантируется, что текущий уровень образования соискателя всегда находится в первых 2ух слов и начинается с заглавной буквы. Воспользуйтесь этим.

*Совет: проверяйте полученные категории, например, с помощью метода unique()*

In [ ]:
def get_education (level):
    level = ' '.join(level.split(' ')[:3])
    if 'Высшее' in level:
        return 'высшее'
    elif 'Неоконченное высшее' in level:
        return 'неоконченное высшее'
    elif 'Среднее специальное' in level:
        return 'среднее специальное'
    elif 'Среднее образование' in level:
        return 'среднее'
hh_data['Образование'] = hh_data['Образование и ВУЗ'].apply(get_education)
hh_data = hh_data.drop('Образование и ВУЗ', axis=1)

hh_data['Образование'].value_counts()

In [ ]:
hh_data['Образование'].nunique()

Ответ: 559 соискателей имеют высшее образование

2. Теперь нас интересует столбец **"Пол, возраст"**. Сейчас он представлен в формате **<Пол , возраст , дата рождения >**. Например:
* Мужчина , 39 лет , родился 27 ноября 1979 
* Женщина , 21 год , родилась 13 января 2000
Как вы понимаете, нам необходимо выделить каждый параметр в отдельный столбец.

Создайте два новых признака **"Пол"** и **"Возраст"**. При этом важно учесть:
* Признак пола должен иметь 2 уникальных строковых значения: 'М' - мужчина, 'Ж' - женщина. 
* Признак возраста должен быть представлен целыми числами.

Выполните преобразование, ответьте на контрольные вопросы и удалите признак **"Пол, возраст"** из таблицы.

*Совет: обратите внимание на структуру текста в столбце, в части на то, как разделены параметры пола, возраста и даты рождения между собой - символом ' , '. 
Гарантируется, что структура одинакова для всех строк в таблице. Вы можете воспользоваться этим.*

In [ ]:
def get_gender(arg):
    gen_arg_splitted = arg.split(' ')
    if gen_arg_splitted[0] =='Мужчина':
        return 'М'
    elif gen_arg_splitted[0] =='Женщина':
        return 'Ж'

def get_age(arg):
    age_arg_splitted = arg.split(' ')
    year_words=['год', 'года', 'лет']
    for index, item in enumerate (age_arg_splitted):
        if item in year_words:
            return int(age_arg_splitted[index-1])


hh_data['Пол'] = hh_data['Пол, возраст'].apply(get_gender)
hh_data['Возраст'] = hh_data['Пол, возраст'].apply(get_age)
#в соответствии с заданием удалим признак «Пол, возраст» из таблицы
hh_data = hh_data.drop('Пол, возраст', axis=1)
hh_data['Возраст'].describe()

In [ ]:
hh_data['Пол'].nunique()

In [ ]:
round(hh_data['Пол'].value_counts(normalize=True)*100, 2)

Ответ: в данных представлено 19.07 % женских резюме.

In [ ]:
round(hh_data['Возраст'].mean(), 1)

Ответ: средний возраст соискателей равен 32.2 года

3. Следующим этапом преобразуем признак **"Опыт работы"**. Его текущий формат - это: **<Опыт работы: n лет m месяцев, периоды работы в различных компаниях…>**. 

Из столбца нам необходимо выделить общий опыт работы соискателя в месяцах, новый признак назовем "Опыт работы (месяц)"

Для начала обсудим условия решения задачи:
* Во-первых, в данном признаке есть пропуски. Условимся, что если мы встречаем пропуск, оставляем его как есть (функция-преобразование возвращает NaN)
* Во-вторых, в данном признаке есть скрытые пропуски. Для некоторых соискателей в столбце стоит значения "Не указано". Их тоже обозначим как NaN (функция-преобразование возвращает NaN)
* В-третьих, нас не интересует информация, которая описывается после указания опыта работы (периоды работы в различных компаниях)
* В-четвертых, у нас есть проблема: опыт работы может быть представлен только в годах или только месяцах. Например, можно встретить следующие варианты:
    * Опыт работы 3 года 2 месяца…
    * Опыт работы 4 года…
    * Опыт работы 11 месяцев…
    * Учитывайте эту особенность в вашем коде

Учитывайте эту особенность в вашем коде

В результате преобразования у вас должен получиться столбец, содержащий информацию о том, сколько месяцев проработал соискатель.
Выполните преобразование, ответьте на контрольные вопросы и удалите столбец **"Опыт работы"** из таблицы.

In [ ]:
def get_experience(arg):
    if arg is np.nan or arg == 'Не указано':
        return None
    year_words=['год', 'года', 'лет']
    month_words=['месяц', 'месяца', 'месяцев']
    arg_splitted = arg.split(' ')[:7]
    years = 0
    months = 0
    for index, item in enumerate (arg_splitted):
        if item in year_words:
            years = int(arg_splitted[index-1])
        if item in month_words:
            months = int(arg_splitted[index-1])
    return int(years*12 + months)

hh_data['Опыт работы (месяц)'] = hh_data['Опыт работы'].apply(get_experience)
hh_data = hh_data.drop('Опыт работы', axis=1)

hh_data['Опыт работы (месяц)'].median()

Ответ: медианный опыт работы в нашей таблице равен 100 месяцам.

4. Хорошо идем! Следующий на очереди признак "Город, переезд, командировки". Информация в нем представлена в следующем виде: **<Город , (метро) , готовность к переезду (города для переезда) , готовность к командировкам>**. В скобках указаны необязательные параметры строки. Например, можно встретить следующие варианты:

* Москва , не готов к переезду , готов к командировкам
* Москва , м. Беломорская , не готов к переезду, не готов к командировкам
* Воронеж , готов к переезду (Сочи, Москва, Санкт-Петербург) , готов к командировкам

Создадим отдельные признаки **"Город"**, **"Готовность к переезду"**, **"Готовность к командировкам"**. При этом важно учесть:

* Признак **"Город"** должен содержать только 4 категории: "Москва", "Санкт-Петербург" и "город-миллионник" (их список ниже), остальные обозначьте как "другие".

    Список городов-миллионников:
    
   <code>million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']
    </code>
    Инфорация о метро, рядом с которым проживает соискатель нас не интересует.
* Признак **"Готовность к переезду"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к переезду в признаке "Город, переезд, командировки". Например:
    * … , готов к переезду , …
    * … , не готова к переезду , …
    * … , готова к переезду (Москва, Санкт-Петербург, Ростов-на-Дону)
    * … , хочу переехать (США) , …
    
    Нас интересует только сам факт возможности или желания переезда.
* Признак **"Готовность к командировкам"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к командировкам в признаке "Город, переезд, командировки". Например:
    * … , готов к командировкам , … 
    * … , готова к редким командировкам , …
    * … , не готов к командировкам , …
    
    Нас интересует только сам факт готовности к командировке.
    
    Еще один важный факт: при выгрузки данных у некоторых соискателей "потерялась" информация о готовности к командировкам. Давайте по умолчанию будем считать, что такие соискатели не готовы к командировкам.
    
Выполните преобразования и удалите столбец **"Город, переезд, командировки"** из таблицы.

*Совет: обратите внимание на то, что структура текста может меняться в зависимости от указания ближайшего метро. Учите это, если будете использовать порядок слов в своей программе.*

In [ ]:
def get_city(arg):
    million_cities = ['Новосибирск', 'Екатеринбург', 'Нижний Новгород',
                      'Казань', 'Челябинск', 'Омск', 'Самара', 'Ростов-на-Дону',
                      'Уфа', 'Красноярск', 'Пермь', 'Воронеж', 'Волгоград'
                      ]
    city = arg.split(' , ')[0]
    if (city == 'Москва') or (city == 'Санкт-Петербург'):
        return city
    elif city in million_cities:
        return 'город миллионник'
    else:
        return 'другие'

def get_ready_to_move(arg):
    if ('не готов к переезду' in arg) or ('не готова к переезду' in arg):
        return False
    elif 'хочу' in arg:
        return True
    else:
        return True

def get_ready_for_bisiness_trips(arg):
    if ('командировка' in arg):
        if ('не готов к командировкам' in arg) or ('не готова к командировкам' in arg):
            return False
        else:

            return True
    else:
        return False


hh_data['Город'] = hh_data['Город, переезд, командировки'].apply(get_city)
hh_data['Готовность к переезду'] = hh_data['Город, переезд, командировки'].apply(get_ready_to_move)
hh_data['Готовность к командировкам'] = hh_data['Город, переезд, командировки'].apply(get_ready_for_bisiness_trips)
hh_data = hh_data.drop('Город, переезд, командировки', axis=1)

In [ ]:
hh_data.head()

In [ ]:
print(round(hh_data['Город'].value_counts(normalize=True)['Санкт-Петербург'] * 100))

Ответ: 11% соискателей живут в Санкт-Петербурге.

In [ ]:
print(round(hh_data[
                hh_data['Готовность к переезду'] & hh_data['Готовность к командировкам']
                ].shape[0] / hh_data.shape[0] * 100))

Ответ: 32 % соискателей готовы одновременно и к переездам, и к командировкам

5. Рассмотрим поближе признаки **"Занятость"** и **"График"**. Сейчас признаки представляют собой набор категорий желаемой занятости (полная занятость, частичная занятость, проектная работа, волонтерство, стажировка) и желаемого графика работы (полный день, сменный график, гибкий график, удаленная работа, вахтовый метод).
На сайте hh.ru соискатель может указывать различные комбинации данных категорий, например:
* полная занятость, частичная занятость
* частичная занятость, проектная работа, волонтерство
* полный день, удаленная работа
* вахтовый метод, гибкий график, удаленная работа, полная занятость

Такой вариант признаков имеет множество различных комбинаций, а значит множество уникальных значений, что мешает анализу. Нужно это исправить!

Давайте создадим признаки-мигалки для каждой категории: если категория присутствует в списке желаемых соискателем, то в столбце на месте строки рассматриваемого соискателя ставится True, иначе - False.

Такой метод преобразования категориальных признаков называется One Hot Encoding и его схема представлена на рисунке ниже:
<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/ohe.jpg>
Выполните данное преобразование для признаков "Занятость" и "График", ответьте на контрольные вопросы, после чего удалите их из таблицы

In [ ]:
employments = ['полная занятость', 'частичная занятость', 'проектная работа', 'волонтерство', 'стажировка']
charts = ['полный день', 'сменный график', 'гибкий график', 'удаленная работа', 'вахтовый метод']
#Запустим цикл по листам по занятости и графику с применением лямбда функции:
for employment, chart in zip(employments, charts):
    hh_data[employment] = hh_data['Занятость'].apply(lambda x: employment in x)
    hh_data[chart] = hh_data['График'].apply(lambda x: chart in x)
#Удаляем ненужные колонки:
hh_data = hh_data.drop('Занятость', axis=1)
hh_data = hh_data.drop('График', axis=1)
hh_data.head()

In [ ]:
hh_data[(hh_data['проектная работа']==True)&(hh_data['волонтерство']==True)].shape[0]

Ответ: 436 человек ищут проектную работу и волонтёрство

In [ ]:
hh_data[(hh_data['вахтовый метод']==True)&(hh_data['гибкий график']==True)].shape[0]

Ответ: 2311 человек хотят работать вахтовым методом и с гибким графиком

6. (2 балла) Наконец, мы добрались до самого главного и самого важного - признака заработной платы **"ЗП"**. 
В чем наша беда? В том, что помимо желаемой заработной платы соискатель указывает валюту, в которой он бы хотел ее получать, например:
* 30000 руб.
* 50000 грн.
* 550 USD

Нам бы хотелось видеть заработную плату в единой валюте, например, в рублях. Возникает вопрос, а где взять курс валют по отношению к рублю?

На самом деле язык Python имеет в арсенале огромное количество возможностей получения данной информации, от обращения к API Центробанка, до использования специальных библиотек, например pycbrf. Однако, это не тема нашего проекта.

Поэтому мы пойдем в лоб: обратимся к специальным интернет-ресурсам для получения данных о курсе в виде текстовых файлов. Например, MDF.RU, данный ресурс позволяет удобно экспортировать данные о курсах различных валют и акций за указанные периоды в виде csv файлов. Мы уже сделали выгрузку курсов валют, которые встречаются в наших данных за период с 29.12.2017 по 05.12.2019. Скачать ее вы можете **на платформе**

Создайте новый DataFrame из полученного файла. В полученной таблице нас будут интересовать столбцы:
* "currency" - наименование валюты в ISO кодировке,
* "date" - дата, 
* "proportion" - пропорция, 
* "close" - цена закрытия (последний зафиксированный курс валюты на указанный день).


Перед вами таблица соответствия наименований иностранных валют в наших данных и их общепринятых сокращений, которые представлены в нашем файле с курсами валют. Пропорция - это число, за сколько единиц валюты указан курс в таблице с курсами. Например, для казахстанского тенге курс на 20.08.2019 составляет 17.197 руб. за 100 тенге, тогда итоговый курс равен - 17.197 / 100 = 0.17197 руб за 1 тенге.
Воспользуйтесь этой информацией в ваших преобразованиях.

<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/table.jpg>


Осталось только понять, откуда брать дату, по которой определяется курс? А вот же она - в признаке **"Обновление резюме"**, в нем содержится дата и время, когда соискатель выложил текущий вариант своего резюме. Нас интересует только дата, по ней бы и будем сопоставлять курсы валют.

Теперь у нас есть вся необходимая информация для того, чтобы создать признак "ЗП (руб)" - заработная плата в рублях.

После ответа на контрольные вопросы удалите исходный столбец заработной платы "ЗП" и все промежуточные столбцы, если вы их создавали.

Итак, давайте обсудим возможный алгоритм преобразования: 
1. Перевести признак "Обновление резюме" из таблицы с резюме в формат datetime и достать из него дату. В тот же формат привести признак "date" из таблицы с валютами.
2. Выделить из столбца "ЗП" сумму желаемой заработной платы и наименование валюты, в которой она исчисляется. Наименование валюты перевести в стандарт ISO согласно с таблицей выше.
3. Присоединить к таблице с резюме таблицу с курсами по столбцам с датой и названием валюты (подумайте, какой тип объединения надо выбрать, чтобы в таблице с резюме сохранились данные о заработной плате, изначально представленной в рублях). Значение close для рубля заполнить единицей 1 (курс рубля самого к себе)
4. Умножить сумму желаемой заработной платы на присоединенный курс валюты (close) и разделить на пропорцию (обратите внимание на пропуски после объединения в этих столбцах), результат занести в новый столбец "ЗП (руб)".

In [ ]:
exrate_data = pd.read_csv('data/ExchangeRates.csv', sep = ',') 

def salary_func(arg):
    salary = float(arg.split(' ')[0])
    return salary
#print(hh_data['валюта'].unique())
def currency_func(arg):
    #словарь возможных значений валют
    currency_dict = {'руб': 'RUB', 'белруб': 'BYN', 'KZT': 'KZT', 'EUR': 'EUR', 'USD': 'USD', 'грн': 'UAH', 'сум': 'UZS', 'KGS': 'KGS', 'AZN': 'AZN'}
    currency = arg.split(' ')[1].replace('.', '') #выделение первого аргумента из строки, удаление точки из названия валюты
    return currency_dict[currency] #возвращает значение словаря по ключу(аргументу)
hh_data['желаемая ЗП'] = hh_data['ЗП'].apply(salary_func) #создание столбца с желаемой суммой ЗП
hh_data['валюта'] = hh_data['ЗП'].apply(currency_func) #создание столбца с валютой желаемой ЗП
exrate_data['date'] = pd.to_datetime(exrate_data['date'], dayfirst=True).dt.date #изменение формата столбца с датой (только дата)
hh_data['Обновление резюме'] = pd.to_datetime(hh_data['Обновление резюме'], dayfirst=True).dt.date #изменение формата столбца с датой (только дата)#объединение двух баз данных (подстановка значений из таблицы с курсами валют по дате и валюте в основную таблицу)
hh_df = hh_data.merge(exrate_data,
                       left_on=['валюта', 'Обновление резюме'], #признаки, по которым ищем данные в основной таблице
                       right_on=['currency', 'date'], #признаки, по которым подставляем данные из таблицы с курсами валют
                       how='left') #все значения из основной таблицы#заполнение пустых значений "1" (для рублей)
hh_df['close'] = hh_df['close'].fillna(1)
hh_df['proportion'] = hh_df['proportion'].fillna(1)
hh_df['ЗП (руб)'] = hh_df['close'] * hh_df['желаемая ЗП']/hh_df['proportion']
#удалим временные столбцы
hh_df = hh_df.drop(['currency', 'per', 'date', 'time', 'vol'], axis=1)
#найдем значение желаемой медианной заработная плата соискателей в нашей таблице (в рублях)
hh_df['ЗП (руб)'].median()

Ответ: 59 тыс. руб. медианная заработная плата соискателей в нашей таблице

In [ ]:
hh_df.head()

# Исследование зависимостей в данных

1. Постройте распределение признака **"Возраст"**. Опишите распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится возраст большинства соискателей? Есть ли аномалии для признака возраста, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
df = hh_df
fig = px.histogram(df,
                   x='Возраст',
                   marginal="box",
                   title='Распределение возраста',
                   hover_data=df.columns)
fig.update_layout(yaxis_title='Количество человек')
fig.show()
fig.write_html("plotly/age distribution (marginal).html")

In [ ]:
# строим распределение признака «Возраст», используя гистограмму
bx = hh_df['Возраст'].plot(
    kind='hist',
    grid=True,
    figsize=(8, 6),
    style="darkgrid",   
    )
# обозначим оси
bx.set_xlabel('Возраст')
bx.set_ylabel('Количество соискателей')
bx.set_title('Распределение признака «Возраст»', fontsize=16)
plt.show()

In [ ]:
fig = px.box(data_frame=hh_df,
x = 'Возраст', 
title='Распределение признака «Возраст»'
)
fig.show()
fig.write_html("plotly/age distribution.html")

In [ ]:
#найдем модальное значение возраста соискателей 
hh_df['Возраст'].mode()[0]

Ответ: модальное значение возраста соискателей (мода распределения) равна 30 годам.

Значение признака "Возраст" соискателей находится в интервале от 14 лет(минимум) до 100 лет.

Максимум (100 лет), безусловно, является аномальным признаком.

2. Постройте распределение признака **"Опыт работы (месяц)"**. Опишите данное распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится опыт работы большинства соискателей? Есть ли аномалии для признака опыта работы, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
df = hh_df
fig = px.histogram(df,
                   x='Опыт работы (месяц)',
                   marginal="box",
                   title='Распределение опыта работы',
                   hover_data=df.columns)
fig.update_layout(yaxis_title='Количество соискателей')
fig.show()
fig.write_html("plotly/work experience (marginal).html")

In [ ]:
# строим распределение опыта работы (в месяцах), используя гистограмму
bx = hh_df['Опыт работы (месяц)'].plot(
    kind='hist',
    grid=True,
    figsize=(8, 6),
    style="darkgrid",   
    )
# обозначим оси
bx.set_xlabel('Опыт работы (месяц')
bx.set_ylabel('Количество соискателей')
bx.set_title('Распределение опыта работы (в месяцах)', fontsize=16)
plt.show()

In [ ]:
fig = px.box(data_frame=hh_df,
x = 'Опыт работы (месяц)', 
title='Распределение признака «Опыт работы»'
)
fig.show()
fig.write_html("plotly/work experience.html")

Ответ: максимальный опыт работы равен 1188 месяцев (или 99 лет) - явный выброс.

Значние признака  "опыт работы" работы большинства соискателей находится в интервале от 1 месяца(мининум) до 1188 месяцев.

Опыт работы 1188 месяцев (максимум) (или 99 лет), безусловно, является аномальным признаком.

3. Постройте распределение признака **"ЗП (руб)"**. Опишите данное распределение, отвечая на следующие вопросы: каковы предельные значения признака, в каком примерном интервале находится заработная плата большинства соискателей? Есть ли аномалии для признака ЗП? Обратите внимание на гигантские размеры желаемой заработной платы.
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
df = hh_df
fig = px.histogram(df,
                   x='ЗП (руб)',
                   marginal="box",
                   title='Распределение заработной платы',
                   hover_data=df.columns)
fig.update_layout(yaxis_title='Количество соискателей')
fig.show()
fig.write_html("plotly/distribution of salary (marginal).html")

In [ ]:
# строим распределение признака «ЗП (руб)», используя гистограмму
bx = hh_df['ЗП (руб)'].plot(
    kind='hist',
    grid=True,
    figsize=(8, 6),
    style="darkgrid",   
    )
# обозначим оси
bx.set_xlabel('ЗП (руб)')
bx.set_ylabel('Количество соискателей')
bx.set_title('Распределение заработной платы', fontsize=16)
plt.show()

In [ ]:
fig = px.box(data_frame=hh_df,
x = 'ЗП (руб)', 
title='Распределение заработной платы',
#width=1000
)
fig.show()
fig.write_html("plotly/distribution of salary.html")

In [ ]:
#проверяем, сколько соискателей требуют заработную плату выше 1 миллиона рублей
hh_df[hh_df['ЗП (руб)']>1e6].shape[0]

Ответ: по графику определяем, затем проверяем с помощью метода shape, что заработную плату выше 1 миллиона рублей требуют 5 соискателей.

4. Постройте диаграмму, которая показывает зависимость **медианной** желаемой заработной платы (**"ЗП (руб)"**) от уровня образования (**"Образование"**). Используйте для диаграммы данные о резюме, где желаемая заработная плата меньше 1 млн рублей.
*Сделайте выводы по представленной диаграмме: для каких уровней образования наблюдаются наибольшие и наименьшие уровни желаемой заработной платы? Как вы считаете, важен ли признак уровня образования при прогнозировании заработной платы?*

In [ ]:
bar_hh = hh_df[hh_df['ЗП (руб)']<1e6].groupby('Образование', as_index=False).median()
fig = px.bar(
    data_frame = bar_hh,
    x='Образование',
    y='ЗП (руб)',
    color='Образование',
    orientation='v',
    height=500, #высота
    width=700, #ширина
    title='Зависимость медианной  заработной платы от уровня образования'
)
#отображаем его
fig.show()
fig.write_html("plotly/dependence of salary on education.html")

Ответ: высшее образование оплачивается выше всех по медианному показателю (60 тыс. руб).

Наименьшиие уровни желаемой заработной платы наблюдаются для среднего и среднеспециального образования (40 тыс. руб).

При прогнозировании заработной платы определенно важен признак уровня образования.

5. Постройте диаграмму, которая показывает распределение желаемой заработной платы (**"ЗП (руб)"**) в зависимости от города (**"Город"**). Используйте для диаграммы данные о резюме, где желая заработная плата меньше 1 млн рублей.
*Сделайте выводы по полученной диаграмме: как соотносятся медианные уровни желаемой заработной платы и их размах в городах? Как вы считаете, важен ли признак города при прогнозировании заработной платы?*

In [ ]:
box_hh = hh_df[hh_df['ЗП (руб)']<1e6]

fig = px.box(data_frame=box_hh,
x = 'ЗП (руб)',
color = 'Город',
title='Распределение заработной платы по городам'
)
fig.show()
fig.write_html("plotly/distribution of salary by city.html")

Ответ: в категории городов "другие" зафиксирован наибольший показатель желаемой заработной
платы (~924 тысячи рублей).

В Москве медианный уровни желаемой заработной платы (85 тыс. руб.) значительно выше, чем в других городах(категориях): Санкт Петербург - 60 тыс. руб., города-миллионники 40 тыс. руб., другие города - 40тыс. руб. Как видим для городов-миллионников этот показатель не отличается от "других" городов. Для показателей размаха ЗП найденная зависимость также выполняется: самые высокие зарплаты соискатели запрашивают в Москве (60-150 тыс. руб.), затем идет Санкт-Петербург (45-85 тыс. руб.), для остальных категорий эти показатели не отличаются (30-60 тыс. руб).

Исходя из вышесказанного можно сделать вывод, что признак города при прогнозировании заработной платы важен только в том случае, если речь идет о Москве или Санкт - Петербурге.

6. Постройте **многоуровневую столбчатую диаграмму**, которая показывает зависимость медианной заработной платы (**"ЗП (руб)"**) от признаков **"Готовность к переезду"** и **"Готовность к командировкам"**. Проанализируйте график, сравнив уровень заработной платы в категориях.

In [ ]:
bar_hh_trip = hh_df.groupby(by=['Готовность к переезду', 'Готовность к командировкам'], as_index=False)['ЗП (руб)'].median()
bar_hh_trip['Готовность к переезду'] = bar_hh_trip['Готовность к переезду'].map({True: 'Готов', False: 'не готов'})
bar_hh_trip['Готовность к командировкам'] = bar_hh_trip['Готовность к командировкам'].map({True: 'Готов', False: 'не готов'})
fig = px.bar(
    data_frame = bar_hh_trip,
    x = 'ЗП (руб)',
    y = 'Готовность к переезду',
    color = 'Готовность к командировкам',
    barmode='group',
	title='Зависимость медианной зарплаты от готовности к переезду и командировкам'
)  
fig.show()
fig.write_html("plotly/salary and travel.html")

Ответ: медианная заработная плата соискателей, готовых и к переезду, и к
командировкам равна 66 тыс. руб.

7. Постройте сводную таблицу, иллюстрирующую зависимость **медианной** желаемой заработной платы от возраста (**"Возраст"**) и образования (**"Образование"**). На полученной сводной таблице постройте **тепловую карту**. Проанализируйте тепловую карту, сравнив показатели внутри групп.

In [ ]:
pivot = hh_df.pivot_table(
    index = 'Образование',
    columns = 'Возраст',
    values = 'ЗП (руб)',
    aggfunc = 'median',
    fill_value = 0
)
fig = px.imshow(
    pivot,
    aspect = 'auto',
    color_continuous_scale='greens',
    title = 'Медианная ЗП в зависимости от образования и возраста'
)
fig.show()
fig.write_html("plotly/salary dependent on age.html")

Cамый быстрый карьерный рост (то есть интенсивность роста заработной платы наибольшая) наблюдается для категорий соискателей с высшим образованием. Исключим из рассмотрения явно аномальные признаки (зарплата выше 100 тыс. руб. для соискателей 16-18 летнего возраста) и получим, что соискатели с высшим образованием уже в возрасте 40 лет могут рассчитывать на ЗП свыше 90 тыс. руб., в то время как работники с иным уровнем образования в этом возрасте могут претендовать на ЗП не выше 60 тыс. руб.

8. Постройте **диаграмму рассеяния**, показывающую зависимость опыта работы (**"Опыт работы (месяц)"**) от возраста (**"Возраст"**). Опыт работы переведите из месяцев в года, чтобы признаки были в едином масштабе. Постройте на графике дополнительно прямую, проходящую через точки (0, 0) и (100, 100). Данная прямая соответствует значениям, когда опыт работы равен возрасту человека. Точки, лежащие на этой прямой и выше нее - аномалии в наших данных (опыт работы больше либо равен возрасту соискателя)

In [ ]:
fig = plt.figure(figsize=(10, 5))
scatter_data = hh_df.copy()
scatter_data['Опыт работы (год)'] = scatter_data['Опыт работы (месяц)']/12
sns.lineplot(x=[0, 100], y=[0, 100])
ax = sns.scatterplot(
    data=scatter_data, 
    x='Возраст',
    y='Опыт работы (год)',
)
ax.set_title('Зависимость опыта работы от возраста');

In [ ]:
#проверим, сколько точек лежат над прямой
print(scatter_data['Опыт работы (год)'][scatter_data['Опыт работы (год)'] >= scatter_data['Возраст']].count())

Ответ: 7 точек лежат строго выше построенной прямой. Это аномальные значения, ведь возраст не может быть меньше опыта работы (и даже равен ему). Такие данные нуждаются в очистке.

**Дополнительные баллы**

Для получения 2 дополнительных баллов по разведывательному анализу постройте еще два любых содержательных графика или диаграммы, которые помогут проиллюстрировать влияние признаков/взаимосвязь между признаками/распределения признаков. Приведите выводы по ним. Желательно, чтобы в анализе участвовали признаки, которые мы создавали ранее в разделе "Преобразование данных".

Построим круговую диаграмму, показывающую, кто чаще ищет работу: мужчины или женщины

In [ ]:
fig = px.pie(
    data_frame=hh_df,
    names='Пол',
    title="Соотношение мужских и женских резюме, опубликованных на HeadHunter",
    height=500,
    width=700,
)
fig.show()
fig.write_html("plotly/men and women.html")

Ответ: из диаграммы видно, что женских резюме на рынке вакансий меньше 20%, что говорит о том, что женщины в четыре раза реже меняют работу, чем мужчины. Можно так же сделать предположение о том, что гораздо больше женщин, чем мужчин находится в статусе самозанятых, так что их резюме не попадают на рынки вакансий.

Теперь узнаем, кто же больше зарабатывает: работающие вахтовым методом мужчины или женщины

In [ ]:
bar_shift_work = hh_df.groupby(by=['вахтовый метод', 'Пол'], as_index=False)['ЗП (руб)'].mean()
fig = px.bar(
    data_frame = bar_shift_work,
    x = 'вахтовый метод',
    y = 'ЗП (руб)',
    color = 'Пол',
    orientation='v',
    height=500,
    width=700,
    barmode='group',
	title='Зависимость средней зарплаты от пола и метода работы'
)  
fig.show()
fig.write_html("plotly/salary, gender and working method.html")

Ответ: из диаграммы видно, что вахтовики-мужчины (69 тыс. руб) как и вахтовики женщины в среднем зарабатывают меньше, чем прочие соискатели вакансий (81 тыс. руб.), стой разницей, что у вахтовиков-женщин эта разница не так заментна (57 против 60 тыс. руб.). Надо отметить, что категория невахтовых рабочих довольно многочисленна и разнообразна (сюда входят соискатели от рабочих и специалистов до руководителей высшего звена, директоров компаний и т.д.), поэтому сравнение их заработной платы с заработной платой вахтовиков (ЗП которы имеет более четкие границы) весьма условно.

# Очистка данных

1. Начнем с дубликатов в наших данных. Найдите **полные дубликаты** в таблице с резюме и удалите их.

In [ ]:
dupl_columns = list(hh_df.columns)
mask = hh_df.duplicated(subset=dupl_columns)
hh_duplicates = hh_df[mask]
print(f'Число найденных дубликатов: {hh_duplicates.shape[0]}')

hh_df = hh_df.drop_duplicates(subset=dupl_columns)
print(f'Результирующее число записей: {hh_df.shape[0]}')

Ответ: найден 161 дубликат.

2. Займемся пропусками. Выведите информацию **о числе пропусков** в столбцах.

In [ ]:
print(hh_df.isnull().sum())

In [ ]:
print(hh_df['Опыт работы (месяц)'].isnull().sum())

Ответ: в столбце «Опыт работы (месяц)» 168 пропусков

3. Итак, у нас есть пропуски в 3ех столбцах: **"Опыт работы (месяц)"**, **"Последнее/нынешнее место работы"**, **"Последняя/нынешняя должность"**. Поступим следующим образом: удалите строки, где есть пропуск в столбцах с местом работы и должностью. Пропуски в столбце с опытом работы заполните **медианным** значением.

In [ ]:
hh_df = hh_df.dropna(how='any', axis=0, subset = ['Последняя/нынешняя должность', 'Последнее/нынешнее место работы'])

values = {
    'Опыт работы (месяц)':hh_df['Опыт работы (месяц)'].median()
}
hh_df = hh_df.fillna(values)

round(hh_df['Опыт работы (месяц)'].mean())

In [ ]:
print(hh_df.isnull().sum())

Ответ: результирующее среднее значение в столбце «Опыт работы (месяц)» после заполнения пропусков равно 114 месяцам.

4. Мы добрались до ликвидации выбросов. Сначала очистим данные вручную. Удалите резюме, в которых указана заработная плата либо выше 1 млн. рублей, либо ниже 1 тыс. рублей.

In [ ]:
hh_releases = hh_df[(hh_df['ЗП (руб)'] > 1e6) | (hh_df['ЗП (руб)'] < 1e3)]
display(hh_releases.shape[0])

Ответ: найдено 89 выбросов

5. В процессе разведывательного анализа мы обнаружили резюме, в которых **опыт работы в годах превышал возраст соискателя**. Найдите такие резюме и удалите их из данных

In [ ]:
hh_df['Опыт работы (год)'] = hh_df['Опыт работы (месяц)']/12
outliers = hh_df[hh_df['Опыт работы (год)'] > hh_df['Возраст']]
print(outliers.shape[0])

hh_df = hh_df.drop(outliers.index, axis=0)
hh_df = hh_df.drop(['Опыт работы (год)'], axis=1)
print(f'Результирующее число записей: {hh_df.shape[0]}')

Ответ: найдено 7 выбросов (резюме, в которых опыт работы превышает возраст соискателя)

6. В результате анализа мы обнаружили потенциальные выбросы в признаке **"Возраст"**. Это оказались резюме людей чересчур преклонного возраста для поиска работы. Попробуйте построить распределение признака в **логарифмическом масштабе**. Добавьте к графику линии, отображающие **среднее и границы интервала метода трех сигм**. Напомним, сделать это можно с помощью метода axvline. Например, для построение линии среднего будет иметь вид:

`histplot.axvline(log_age.mean(), color='k', lw=2)`

В какую сторону асимметрично логарифмическое распределение? Напишите об этом в комментарии к графику.
Найдите выбросы с помощью метода z-отклонения и удалите их из данных, используйте логарифмический масштаб. Давайте сделаем послабление на **1 сигму** (возьмите 4 сигмы) в **правую сторону**.

Выведите таблицу с полученными выбросами и оцените, с каким возрастом соискатели попадают под категорию выбросов?

In [ ]:
#в логарифмическом масштабе
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(15, 4))
log_age= np.log(hh_df['Возраст'] + 1)

histplot = sns.histplot(data = log_age, bins=30, ax=axes[0])
histplot.set_title('Распределение возраста');

boxplot = sns.boxplot(data=log_age, ax=axes[1], orient='h');
boxplot.set_title('Распределение возраста');

histplot.axvline(log_age.mean(), color='k', lw=2)
histplot.axvline(log_age.mean()+ 3 * log_age.std(), color='k', ls='--', lw=2)
histplot.axvline(log_age.mean()- 3 * log_age.std(), color='k', ls='--', lw=2);

boxplot.axvline(log_age.mean(), color='k', lw=2)
boxplot.axvline(log_age.mean()+ 3 * log_age.std(), color='k', ls='--', lw=2)
boxplot.axvline(log_age.mean()- 3 * log_age.std(), color='k', ls='--', lw=2);

In [ ]:
def outliers_z_score_mod(data, feature, log_scale=True, left=3, right=4):
    if log_scale:
        x = np.log(data[feature]+1)
    else:
        x = data[feature]
    mu = x.mean()
    sigma = x.std()
    lower_bound = mu - left * sigma
    upper_bound = mu + right * sigma
    outliers = data[(x < lower_bound) | (x > upper_bound)]
    cleaned = data[(x > lower_bound) & (x < upper_bound)]
    return outliers, cleaned

outliers, cleaned = outliers_z_score_mod(hh_df, 'Возраст', log_scale=True)
print(f'Число выбросов по методу z-отклонения: {outliers.shape[0]}')
print(f'Результирующее число записей: {cleaned.shape[0]}')

In [ ]:
outliers.head()

In [ ]:
outliers['Возраст']

Графики несимметричны, сдвинуты вправо относительно средней оси и границ.

Ответ: под категорию выбросов попали 3 соискателя: один - в возрасте 100 лет и 2 в возрасте 15 лет. Безусловно, это сомнительные резюме: 100-летний Frontend-разработчик на Freelance, 15 летние тестировщик игр и менеджер по работе с клиентами. Работадателю такие резюме не стоит принимать во внимание.